apiVersion: apps/v1
kind: Deployment
metadata:
  name: avn-otus-hw1-architect-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avn-otus-hw1-architect-app
  template:
    metadata:
      labels:
        app: avn-otus-hw1-architect-app
    spec:
      containers:
        - name: avn-otus-hw1-architect
          image: avnikulin/otus-hw1-architect
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2