---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" .Values.applicationName }}
data:
  db.database: {{ .Values.db.name }}
  db.username: {{ .Values.db.username }}
  db.url:  {{ printf "jdbc:postgresql://%s-postgres:%s/%s" .Values.applicationName (toString .Values.db.port) .Values.db.name }}
  db.driver: org.postgresql.Driver
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" .Values.applicationName }}
type: Opaque
data:
  db.password: {{ .Values.db.password }}