---
apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-postgres" .Values.applicationName }}
  labels:
    app: {{ printf "%s-postgres" .Values.applicationName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.db.port }}
  selector:
    app: {{ printf "%s-postgres" .Values.applicationName }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-postgres" .Values.applicationName }}
spec:
  serviceName: {{ printf "%s-postgres" .Values.applicationName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-postgres" .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-postgres" .Values.applicationName }}
    spec:
      containers:
        - name: {{ printf "%s-postgres" .Values.applicationName }}
          image: postgres:latest
          ports:
            - containerPort: {{ .Values.db.port }}
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-config" .Values.applicationName }}
                  key: db.database
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-config" .Values.applicationName }}
                  key: db.username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secret" .Values.applicationName }}
                  key: db.password
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi