apiVersion: apps/v1
kind: Deployment
metadata:
  name: avn-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: avn-app
  template:
    metadata:
      labels:
        app: avn-app
    spec:
      containers:
        - name: avn-otus-hw1-architect
          image: avnikulin/otus-hw1-architect:1.1.0
          ports:
            - containerPort: 8000
          env:
            - name: spring_datasource_url
              valueFrom:
                configMapKeyRef:
                  name: avn-app-config
                  key: db.url
            - name: spring_datasource_username
              valueFrom:
                configMapKeyRef:
                  name: avn-app-config
                  key: db.username
            - name: spring_datasource_password
              valueFrom:
                secretKeyRef:
                  name: avn-app-secret
                  key: db.password
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2