{
 "title": "AVN app",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "NGINX RPC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count{host=\"arch.homework\"}[1m]))"
    }
   ]
  },
  {
   "title": "User Service RPS By Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(http_server_requests_seconds_count{uri=~\"/users.*\"}[1m]))"
    },
    {
     "expr": "sum (rate(http_server_requests_seconds_count{uri=~\"/users.*\"}[1m]))",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "NGINX Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_response_duration_seconds_sum{host=\"arch.homework\"}[1m])))/(sum(rate(nginx_ingress_controller_response_duration_seconds_count{host=\"arch.homework\"}[1m])))*10000"
    }
   ]
  },
  {
   "title": "User Service Latency By Method (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (method) (rate(http_server_requests_seconds_sum{uri=~\"/users.*\"}[1m])))/(sum by (method) (rate(http_server_requests_seconds_count{uri=~\"/users.*\"}[1m])))*10000"
    },
    {
     "expr": "(sum (rate(http_server_requests_seconds_sum{uri=~\"/users.*\"}[1m])))/(sum (rate(http_server_requests_seconds_count{uri=~\"/users.*\"}[1m])))*10000",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "NGINX Quantile (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\"}[1m])))*1000",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\"}[1m])))*1000",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"arch.homework\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "User Service Histogram_quantile (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{uri=~\"/users.*\"}[1m])))*1000",
     "legendFormat": "quantile 50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_server_requests_seconds_bucket{uri=~\"/users.*\"}[1m])))*1000",
     "legendFormat": "quantile 95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{uri=~\"/users.*\"}[1m])))*1000",
     "legendFormat": "quantile 99"
    }
   ]
  },
  {
   "title": "NGINX Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.*\"}[1m]))/sum(rate(nginx_ingress_controller_request_duration_seconds_count{status!~\"5.*\"}[1m]))",
     "legendFormat": "Error percentage"
    }
   ]
  },
  {
   "title": "Error 500 rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/users.*\", status=~\"5.*\"}[1m]))/sum(rate(http_server_requests_seconds_count{uri=~\"/users.*\", status!~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error 400 rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/users.*\", status=~\"4.*\"}[1m]))/sum(rate(http_server_requests_seconds_count{uri=~\"/users.*\", status=~\"2.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod)(rate(jvm_gc_pause_seconds_sum[1m]))/sum by (pod)(rate(jvm_gc_pause_seconds_count[1m])))"
    }
   ]
  }
 ]
}