---
apiVersion: v1
kind: Service
metadata:
  name: avn-postgres
  labels:
    app: avn-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: avn-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: avn-postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: avn-postgres
  template:
    metadata:
      labels:
        app: avn-postgres
    spec:
      containers:
        - name: avn-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: avn-app-config
                  key: db.database
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: avn-app-config
                  key: db.username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: avn-app-secret
                  key: db.password
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi