apiVersion: v1
kind: Service
metadata:
  name: avn-app
  labels:
    app.kubernetes.io/name: avn-app
spec:
  selector:
    app: avn-app
  ports:
    - name: avn-app-port
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort