---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avn-app-config
data:
  db.database: otushw1
  db.username: otushw1
  db.url: jdbc:postgresql://avn-postgres:5432/otushw1
  db.driver: org.postgresql.Driver
---
apiVersion: v1
kind: Secret
metadata:
  name: avn-app-secret
type: Opaque
data:
  db.password: c2VjcmV0X3Bhc3N3b3Jk