apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: avn-app-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: avn-app
  endpoints:
    - port: avn-app-port
      path: /actuator/prometheus
      interval: 10s
